#!/sbin/sh

console=$(cat /tmp/console)
[ "$console" ] || console=/proc/$$/fd/1

print() {
	if [ "$1" ]; then
		echo "ui_print - $1" > "$console"
	else
		echo "ui_print  " > "$console"
	fi
	echo
}

abort() {
	[ "$1" ] && {
		print "Error: $1!"
		print "Aborting..."
	}
	exit 1
}

enabled=false
if [ "$enabled" = true ] ; then
{
	. "$env"

	temp=/tmp/anykernel/ramdisk

	print "Disabling forced encryption in the fstab..."
	found_fstab=false

	for fstab in fstab.qcom; do
		[ -f $temp/$fstab ] || continue
		print "Found fstab: $fstab"
		sed -i "
			s/\b\(forceencrypt\|forcefdeorfbe\)=/encryptable=/g
		" "$temp/$fstab"
		found_fstab=true
		print "Script finished"
	done

	$found_fstab || print "Unable to find the fstab!" && print ""
}
else
{
	print "Script disabled by default" && print ""
}
fi

exit 0
