#!/sbin/sh

console=$(cat /tmp/console)
[ "$console" ] || console=/proc/$$/fd/1

print() {
	if [ "$1" ]; then
		echo "ui_print - $1" > "$console"
	else
		echo "ui_print  " > "$console"
	fi
	echo
}

abort() {
	[ "$1" ] && {
		print "Error: $1!"
		print "Aborting..."
	}
	exit 1
}

enabled=false
if [ "$enabled" = true ] ; then
{
	temp=/tmp/anykernel
	MAGISKBIN=/tmp/anykernel/tools/magiskboot

	print "Disabling avb-verity in the fstab..."

	if [ -f $temp/dtb ] && [ -f $MAGISKBIN ] ; then
	{
		print "Found dtbo image: dtb"
		$MAGISKBIN --dtb-patch $temp/dtb
		print "Script finished" && print ""
	}
	else
	{
		print "Unable to find the dtb!" && print ""
	}
	fi
}
else
{
	print "Script disabled by default" && print ""
}
fi

exit 0
